[package]
edition = "2021"
name    = "todo"
version = "0.1.0"

[dependencies]
clap    = { version = "4.5.18", features = ["derive"] }
diesel  = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15.7"
